version: '3.8'

services:
  area_manager:
    build:
      context: .
      dockerfile: Area_Manager/Dockerfile
    container_name: area_manager
    volumes:
      - C:\Users\kamil\Desktop\tilesFolder:/data
    restart: unless-stopped

  mqgateway:
    build:
      context: .
      dockerfile: MQGateway/Dockerfile
    container_name: mqgateway
    restart: unless-stopped

  mqtt_data_collector:
    build:
      context: .
      dockerfile: MQTT_Data_Collector/Dockerfile
    container_name: mqtt_data_collector
    restart: unless-stopped
